controllers:
  main:
    containers:
      app:
        image:
          repository: ghcr.io/wg-easy/wg-easy
          tag: "{{ .Chart.AppVersion }}"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        env:
          LANG: en
          WG_HOST: &host "wg-easy.example.local"
          PORT: &httpPort "51821"
          WG_PORT: &vpnPort "51820"
        envFrom:
          - secret: env

service:
  app:
    primary: true
    controller: main
    type: ClusterIP
    ports:
      http:
        protocol: TCP
        port: *httpPort
        targetPort: *httpPort
  vpn:
    controller: main
    type: LoadBalancer
    ports:
      vpn:
        protocol: UDP
        port: *vpnPort
        targetPort: *vpnPort

ingress:
  app:
    enabled: false
    # Set the ingress class name to use
    # className:
    hosts:
      - host: *host
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls: []
    #  - secretName: wg-easy-tls
    #    hosts:
    #      - wg-easy.example.local

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 100Mi
    advancedMounts:
      main:
        app:
          - path: /etc/wireguard

secrets:
  env:
    stringData:
      PASSWORD_HASH: "$2a$12$xtWSFBRNWQVFAlUwdD0OsuS6oRfRIWiAPEHe4JuQbCWwklHHxfHRu" # secretpass
