apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}-vpn
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.vpn.type }}
  ports:
    - port: {{ .Values.service.vpn.port }}
      targetPort: {{ .Values.service.vpn.targetPort }}
      protocol: UDP
      name: vpn
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}